// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {files} from '../models';

export function GetConfig():Promise<config.Config>;

export function LoadSNTsFromDir(arg1:config.Config):Promise<Array<files.FileData>>;

export function LoadSntFileFromPath(arg1:string):Promise<files.FileData>;

export function OpenFolderDialog():Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveFileOnDesktop(arg1:config.Config,arg2:string,arg3:string):Promise<void>;
